# Generated by Django 4.2.7 on 2023-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('emial', models.EmailField(max_length=200, verbose_name='Email')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefoní číslo')),
                ('mesto', models.CharField(max_length=100, verbose_name='Město')),
                ('ulice', models.CharField(max_length=100, verbose_name='ulice')),
                ('pcs', models.CharField(max_length=5, verbose_name='PSČ')),
            ],
        ),
    ]
