# Generated by Django 4.2.7 on 2023-12-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistka', '0003_uzivatel_cislo_uzivatel_jmeno_uzivatel_mesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pojistka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_pojisteni', models.CharField(choices=[('nemovitost', 'Pojištění nemovitosti'), ('auto', 'Pojištění auta'), ('veci', 'Pojištění věcí'), ('cestovni', 'Cestovní pojištění')], default='nemovitost', max_length=20, verbose_name='Typ pojištění')),
                ('dalsi_pole', models.CharField(max_length=100, verbose_name='Další pole 1')),
                ('dalsi_pole2', models.CharField(max_length=100, verbose_name='Další pole 2')),
            ],
            options={
                'verbose_name': 'Pojištění',
                'verbose_name_plural': 'Pojištění',
            },
        ),
    ]
