# Generated by Django 4.2.7 on 2023-12-01 17:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pojistka', '0005_remove_pojistka_dalsi_pole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzivatel',
            name='pojistky',
            field=models.ManyToManyField(blank=True, related_name='pojistky', to='pojistka.pojistka'),
        ),
        migrations.AlterField(
            model_name='pojistka',
            name='datum_do',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 17, 2, 21, 395688, tzinfo=datetime.timezone.utc), verbose_name='Platnost do'),
        ),
        migrations.AlterField(
            model_name='pojistka',
            name='datum_od',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Platnost od'),
        ),
    ]
