# Generated by Django 4.2.7 on 2023-12-01 17:10

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistka', '0006_uzivatel_pojistky_alter_pojistka_datum_do_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojistka',
            name='uzivatele',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pojistka',
            name='datum_do',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 17, 10, 2, 442225, tzinfo=datetime.timezone.utc), verbose_name='Platnost do'),
        ),
    ]
