# Generated by Django 4.2.7 on 2023-12-01 17:49

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistka', '0008_alter_pojistka_datum_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistka',
            name='datum_do',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 17, 49, 24, 405685, tzinfo=datetime.timezone.utc), verbose_name='Platnost do'),
        ),
        migrations.AlterField(
            model_name='pojistka',
            name='uzivatele',
            field=models.ManyToManyField(blank=True, related_name='uzivatele', to=settings.AUTH_USER_MODEL),
        ),
    ]
