# Generated by Django 4.2.7 on 2023-12-01 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistka', '0010_remove_pojistka_konec_cesty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistka',
            name='datum_do',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 18, 19, 7, 50209, tzinfo=datetime.timezone.utc), verbose_name='Platnost do'),
        ),
    ]
